name: ${artifactId}
main: ${package}.examplepackage.YourSpigotPlugin
version: ${project.version}
author: ${groupId}
api-version: 1.13
description: Example Plugin




#commands:
#    YourCommand:
#        usage: "/<command> <args>"
#        description: Example command
#        aliases: [yourcommandalias]
#        permission: yourplugin.yourpermission
#permissions:
#    YourSpigotPlugin.*:
#        description: Gives all Example Permissions
#        default: false
#        children:
#            yourplugin.yourpermission: true
#    yourplugin.yourpermission:
#        description: Gives access to the example command
#        default: op
